CREATE TABLE ingredients
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    unit        VARCHAR(255),
    quantity    DOUBLE PRECISION,
    image_url   VARCHAR(255),
    expiry_date date,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);
CREATE TABLE pantry_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    ingredient_id BIGINT                                  NOT NULL,
    quantity      DOUBLE PRECISION,
    CONSTRAINT pk_pantry_items PRIMARY KEY (id)
);

ALTER TABLE pantry_items
    ADD CONSTRAINT FK_PANTRY_ITEMS_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredients (id);

ALTER TABLE pantry_items
    ADD CONSTRAINT FK_PANTRY_ITEMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
CREATE TABLE recipe_ingredients
(
    ingredient_id BIGINT NOT NULL,
    recipe_id     BIGINT NOT NULL
);

CREATE TABLE recipes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255),
    instructions        VARCHAR(4000),
    preparation_minutes INTEGER,
    category            VARCHAR(255),
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);

ALTER TABLE recipe_ingredients
    ADD CONSTRAINT fk_recing_on_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (id);

ALTER TABLE recipe_ingredients
    ADD CONSTRAINT fk_recing_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (id);
CREATE TABLE shopping_entries
(
    shopping_list_id BIGINT NOT NULL,
    entry            VARCHAR(255)
);

CREATE TABLE shopping_lists
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_shopping_lists PRIMARY KEY (id)
);

ALTER TABLE shopping_lists
    ADD CONSTRAINT FK_SHOPPING_LISTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE shopping_entries
    ADD CONSTRAINT fk_shopping_entries_on_shopping_list FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists (id);
CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    full_name VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);